#include "dynamic_modules.h"

#include "core/core.h"

#include "main/lunar_sprites.h"

#if defined(WINDOWS_ENABLED)
#define DYNAMIC_EXTENSION "dll"
#elif defined(WEB_ENABLED)
#define DYNAMIC_EXTENSION "wasm"
#else
#define DYNAMIC_EXTENSION "so"
#endif

typedef void (*LSApiInitFun)(LSAPIInterface *p_interface);

typedef struct {
	FlagValue *dump_api;
	FlagValue *dump_api_file;
	Slice *interfaces;
} DynamicModules;

static DynamicModules dynamic_modules;

static Slice *load_native_modules();
static char *get_module_name(String file_path);

void dynamic_modules_init(LSCore *core) {
	api_interface_init();

	FlagManager *flag_manager = core_get_flag_manager(core);

	dynamic_modules.dump_api = flag_manager_register(flag_manager, "dump-api", FLAG_TYPE_BOOL, FLAG_VAL(b, false), "Extract the native API header file.");
	dynamic_modules.dump_api_file = flag_manager_register(flag_manager, "api-file", FLAG_TYPE_STRING, FLAG_VAL(str, "ls_api.h"), "If dump-api is true, extract the native API to this file.");

	dynamic_modules.interfaces = load_native_modules();
}

void dynamic_modules_start() {
	if (dynamic_modules.dump_api->b) {
		ls_printf("Dumping native API to %s\n", dynamic_modules.dump_api_file->str);
		ls_printf("This file is automatically generated. Do not edit it manually.\n");

		char *file_name = ls_str_copy(dynamic_modules.dump_api_file->str);

		char *temp = file_name;
		file_name = ls_str_replace(file_name, ".h", "");
		ls_free(temp);
		temp = file_name;
		file_name = ls_str_replace(file_name, ".c", "");
		ls_free(temp);

		char *header_file = ls_str_format("%s.h", file_name);
		char *source_file = ls_str_format("%s.c", file_name);
		ls_free(file_name);

		char *api_source = ls_str_replace((String)LS_API_SOURCE, "@API_HEADER@", header_file);

		if (!os_write_file(source_file, api_source, ls_str_length(api_source))) {
			ls_log_fatal("Failed to write file %s\n", source_file);
		}

		ls_free(api_source);

		if (!os_write_file(header_file, (String)LS_API_HEADER, ls_str_length((String)LS_API_HEADER))) {
			ls_log_fatal("Failed to write file %s\n", header_file);
		}

		ls_printf("Wrote native API header to %s and %s\n", header_file, source_file);

		ls_free(header_file);
		ls_free(source_file);

		ls_exit(0);
	}
}

void dynamic_modules_deinit() {
	slice_destroy(dynamic_modules.interfaces);
}

static Slice *load_native_modules() {
	Slice *interfaces = slice_create(16, true);

	Slice *files = os_list_directory("./");

	for (size_t i = 0; i < slice_get_size(files); i++) {
		String file = slice_get(files, i).str;
		char *file_abs = os_path_to_absolute(file);

		char *ext = os_path_get_extension(file_abs);
		if (ext && ls_str_equals(ext, DYNAMIC_EXTENSION)) {
			void *handle = os_open_library(file_abs);
			if (!handle) {
				ls_log(LOG_LEVEL_INFO, "Failed to load module %s\n", file_abs);
				continue;
			}

			char *module_name = get_module_name(file_abs);
			char *register_method = ls_str_format("register_%s_module", module_name);
			ls_free(module_name);

			LSApiInitFun init_function = os_get_library_symbol(handle, "ls_api_init");
			if (!init_function) {
				ls_log(LOG_LEVEL_INFO, "Failed to load module %s\n", file_abs);
				continue;
			}

			init_function(ls_api_interface);

			DynamicModuleRegisterFunc register_function = os_get_library_symbol(handle, register_method);
			ls_free(register_method);

			if (!register_function) {
				ls_log(LOG_LEVEL_INFO, "Failed to load module %s\n", file_abs);
				continue;
			}

			DynamicModuleInterface interface = register_function();
			if (!interface.init || !interface.deinit) {
				ls_log(LOG_LEVEL_INFO, "Failed to load module %s\n", file_abs);
				continue;
			}

			DynamicModuleInterface *interface_ptr = ls_malloc(sizeof(DynamicModuleInterface));
			*interface_ptr = interface;

			slice_append(interfaces, SLICE_VAL(ptr, interface_ptr));
		}
		ls_free(ext);
		ls_free(file_abs);
	}

	slice_destroy(files);

	return interfaces;
}

void initialize_dynamic_modules(ModuleInitializationLevel p_level, void *p_arg) {
	for (size_t i = 0; i < slice_get_size(dynamic_modules.interfaces); i++) {
		DynamicModuleInterface *interface = slice_get(dynamic_modules.interfaces, i).ptr;
		interface->init(p_level, p_arg);
	}
}

void uninitialize_dynamic_modules(ModuleInitializationLevel p_level) {
	for (size_t i = 0; i < slice_get_size(dynamic_modules.interfaces); i++) {
		DynamicModuleInterface *interface = slice_get(dynamic_modules.interfaces, i).ptr;
		interface->deinit(p_level);
	}
}

static char *get_module_name(String file_path) {
	char *file_name = os_path_get_filename(file_path);
	// Find the first . in the file name and replace it with a null terminator.
	String lib_name = ls_str_find(file_name, ".");
	if (lib_name) {
		file_name[lib_name - file_name] = '\0';
	}

	char *module_name = ls_str_replace(file_name, "lib", "");
	ls_free(file_name);

	return module_name;
}