#!/usr/bin/env python

import os

from api_builder import make_dynamic_module_gen

Import("env")
Import("env_modules")

env_dynamic_modules = env.Clone()

make_dynamic_module_gen(env)

env_dynamic_modules.add_source_files(env.modules_sources, "*.c")
env_dynamic_modules.add_source_files(env.modules_sources, "dynamic_modules.gen.c")

Export("env_dynamic_modules")
Export("env")

if env["dynamic_module_test"]:
    SConscript("test/SCsub")
