#!/usr/bin/env python

import os

Import("env")
Import("env_modules")

env_ui = env_modules.Clone()

thirdparty_obj = []

thirdparty_dir = "#thirdparty/"
thirdparty_sources = []
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

module_obj = []

env_ui.add_source_files(module_obj, "*.c")
env.modules_sources += module_obj

env.Depends(module_obj, thirdparty_obj)
