#!/usr/bin/env python

Import("env")

env.main_sources = [
	"lunar_sprites.c",
]

if env["platform"] == "web":
	env.main_sources += [
		"main_loop_web.c",
	]
else:
	env.main_sources += [
		"main_loop.c",
	]

env_main = env.Clone()


if env["tests"]:
	env_main.Append(CPPDEFINES = ["TESTS_ENABLED"])

lib = env_main.add_library("main", env_main.main_sources)
env.Prepend(LIBS = [lib])
