#!/usr/bin/env python

Import("env")

source_files = [
    "display_server.c",
    "window.c",
]

objects = []

for source_file in source_files:
    objects.append(env.Object(source_file))

Return("objects")