#include "native_api.h"

#include "core/core.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct {
	FlagValue *dump_api;
	FlagValue *dump_api_file;

	Slice *api_client_initialization_functions;
	Slice *api_client_uninitialization_functions;
} NativeApi;

static NativeApi native_api;

static void load_api_clieants();

void native_api_init() {
	native_api.dump_api = ls_register_flag("dump-api", FLAG_TYPE_BOOL, FLAG_VAL(b, false), "Extract the native API header file.");
	native_api.dump_api_file = ls_register_flag("api-file", FLAG_TYPE_STRING, FLAG_VAL(str, "ls_api.h"), "If dump-api is true, extract the native API to this file.");

	native_api.api_client_initialization_functions = slice_create(2, false);
	native_api.api_client_uninitialization_functions = slice_create(2, false);

	load_api_clieants();
}

void native_api_init_clients(APIClientInitializationLevel p_level) {
	for (size_t i = 0; i < slice_get_size(native_api.api_client_initialization_functions); i++) {
		APIClientInitializationFunction function = slice_get(native_api.api_client_initialization_functions, i).ptr;
		function(p_level);
	}
}

void native_api_uninit_clients(APIClientInitializationLevel p_level) {
	for (size_t i = 0; i < slice_get_size(native_api.api_client_uninitialization_functions); i++) {
		APIClientInitializationFunction function = slice_get(native_api.api_client_uninitialization_functions, i).ptr;
		function(p_level);
	}
}

void native_api_start() {
	if (native_api.dump_api->b) {
		FILE *file = fopen(native_api.dump_api_file->str, "w");
		if (!file) {
			ls_printf("Failed to open file %s\n", native_api.dump_api_file->str);
			return;
		}

		ls_printf("Dumping native API to %s\n", native_api.dump_api_file->str);
		ls_printf("This file is automatically generated. Do not edit it manually.\n");

		fprintf(file, "%s", LS_API_HEADER);

		fclose(file);

		ls_printf("Wrote native API to %s\n", native_api.dump_api_file->str);

		exit(0);
	}
}

void native_api_deinit() {
	slice_destroy(native_api.api_client_initialization_functions);
	slice_destroy(native_api.api_client_uninitialization_functions);
}

static void load_api_clieants() {
	void *handle = dlopen("./libapi_client.so", RTLD_LAZY);
	if (!handle) {
		ls_log(LOG_LEVEL_INFO, "No API clients found\n");
		return;
	}

	APIClientRegisterFunction register_function = dlsym(handle, "register_api_client");

	if (!register_function) {
		ls_log(LOG_LEVEL_INFO, "No API clients found\n");
		return;
	}

	APIClientInterface api_client = register_function();

	if (!api_client.initialize || !api_client.uninitialize) {
		ls_log(LOG_LEVEL_ERROR, "Failed to load API client\n");
		return;
	}

	slice_append(native_api.api_client_initialization_functions, SLICE_VAL(ptr, api_client.initialize));
	slice_append(native_api.api_client_uninitialization_functions, SLICE_VAL(ptr, api_client.uninitialize));
}