#!/usr/bin/env python

Import("env")

# The HTTP server "targets". Run with "scons p=web serve", or "scons p=web run"
if "serve" in COMMAND_LINE_TARGETS or "run" in COMMAND_LINE_TARGETS:
    from serve import serve
    import os

    port = os.environ.get("LUNAR_WEB_TEST_PORT", 8060)
    try:
        port = int(port)
    except Exception:
        print("LUNAR_WEB_TEST_PORT must be a valid integer")
        sys.exit(255)
    serve(env.Dir("#bin/.web_zip").abspath, port, "run" in COMMAND_LINE_TARGETS)
    sys.exit(0)

web_files = [
    "window.c",
    "os.c",
    "js_methods.c",
]

if env["use_opengl"]:
    web_files += ["webgl.c"]

sys_env = env.Clone()
sys_env.AddJSLibraries([])
sys_env.AddJSExterns([])

if env["javascript_eval"]:
    # TODO: implement this
    # sys_env.AddJSLibraries([])
    pass

for lib in sys_env["JS_LIBS"]:
    sys_env.Append(LINKFLAGS=["--js-library", lib.abspath])
for js in sys_env["JS_PRE"]:
    sys_env.Append(LINKFLAGS=["--pre-js", js.abspath])
for ext in sys_env["JS_EXTERNS"]:
    sys_env["ENV"]["EMCC_CLOSURE_ARGS"] += " --externs " + ext.abspath

build = []
build_targets = ["#bin/lunar_sprites${PROGSUFFIX}.js", "#bin/lunar_sprites${PROGSUFFIX}.wasm", "#bin/lunar_sprites${PROGSUFFIX}.worker.js"]

# We use IDBFS. Since Emscripten 1.39.1 it needs to be linked explicitly.
sys_env.Append(LIBS=["idbfs.js"])
build = sys_env.Program(build_targets, web_files + ["main.c"])

sys_env.Depends(build[0], sys_env["JS_LIBS"])
sys_env.Depends(build[0], sys_env["JS_PRE"])
sys_env.Depends(build[0], sys_env["JS_EXTERNS"])

engine = [
    "js/engine/engine.js",
]
externs = []
js_engine = env.CreateEngineFile("#bin/lunar_sprites${PROGSUFFIX}.engine.js", engine, externs)
env.Depends(js_engine, externs)

wrap_list = [
    build[0],
    js_engine,
]
js_wrapped = env.Textfile("#bin/lunar_sprites", [env.File(f) for f in wrap_list], TEXTFILESUFFIX="${PROGSUFFIX}.wrapped.js")

# 0 - unwrapped js file (use wrapped one instead)
# 1 - wasm file
env.CreateTemplateZip(js_wrapped, build[1], build[2])