#include "native_application.h"

#include "core/core.h"

#include "main/lunar_sprites.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct {
	FlagValue *dump_api;
	FlagValue *dump_api_file;
} NativeApi;

static NativeApi native_api;

static void load_native_application();

void native_application_init(LSCore *core) {
	FlagManager *flag_manager = core_get_flag_manager(core);
	native_api.dump_api = flag_manager_register(flag_manager, "dump-api", FLAG_TYPE_BOOL, FLAG_VAL(b, false), "Extract the native API header file.");
	native_api.dump_api_file = flag_manager_register(flag_manager, "api-file", FLAG_TYPE_STRING, FLAG_VAL(str, "ls_api.h"), "If dump-api is true, extract the native API to this file.");

	load_native_application();
}

void native_application_start() {
	if (native_api.dump_api->b) {
		FILE *file = fopen(native_api.dump_api_file->str, "w");
		if (!file) {
			ls_printf("Failed to open file %s\n", native_api.dump_api_file->str);
			return;
		}

		ls_printf("Dumping native API to %s\n", native_api.dump_api_file->str);
		ls_printf("This file is automatically generated. Do not edit it manually.\n");

		fprintf(file, "%s", LS_API_HEADER);

		fclose(file);

		ls_printf("Wrote native API to %s\n", native_api.dump_api_file->str);

		exit(0);
	}
}

void native_application_deinit() {
}

static void load_native_application() {
	void *handle = dlopen("./libapplication.so", RTLD_LAZY);
	if (!handle) {
		ls_log(LOG_LEVEL_INFO, "No application found\n");
		return;
	}

	NativeApplicationRegisterFunction register_function = dlsym(handle, "register_application");

	if (!register_function) {
		ls_log(LOG_LEVEL_INFO, "No application found\n");
		return;
	}

	ls_set_application_interface(register_function());
}