#!/usr/bin/env python

Import("env")

env.core_sources = []

thirdparty_obj = []

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()

thirdparty_misc_dir = "#thirdparty/misc/"
thirdparty_misc_sources = []
thirdparty_misc_sources = [thirdparty_misc_dir + file for file in thirdparty_misc_sources]
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_misc_sources)

env.core_sources += thirdparty_obj

env.add_source_files(env.core_sources, "*.c")
env.add_source_files(env.core_sources, "version_info.gen.c")

SConscript("types/SCsub")
SConscript("math/SCsub")
SConscript("input/SCsub")
SConscript("os/SCsub")
SConscript("object/SCsub")
SConscript("resource/SCsub")

lib = env.add_library("core", env.core_sources)
env.Prepend(LIBS=[lib])

env.Depends(lib, thirdparty_obj)
