#!/usr/bin/env python

import os
from lua_builders import make_lua_constants_source

Import("env")
Import("env_modules")

env_lua = env_modules.Clone()

thirdparty_obj = []

thirdparty_dir = "#thirdparty/"
thirdparty_sources = [
    "lua/onelua.c",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_lua.Prepend(CPPPATH=[thirdparty_dir + "lua"])

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

module_obj = []

make_lua_constants_source("LS_", [
    "../../core/input/keycodes.h",
    "../../core/math/math.h",
    "../../core/log.h",
], "lua_core_init_constants", "types/lua_core.gen.c")

make_lua_constants_source("RENDERER_", [
    "../../renderer/renderer.h",
], "lua_renderer_init_constants", "types/lua_renderer.gen.c")

env_lua.add_source_files(module_obj, "*.c")
env_lua.add_source_files(module_obj, "types/*.c")
env_lua.add_source_files(module_obj, "types/lua_core.gen.c")
env_lua.add_source_files(module_obj, "types/lua_renderer.gen.c")
env.modules_sources += module_obj

env.Depends(module_obj, thirdparty_obj)
