#!/usr/bin/env python

import os

Import("env")
Import("env_modules")

env_lua = env_modules.Clone()

thirdparty_obj = []

thirdparty_dir = "#thirdparty/"
thirdparty_sources = [
    "lua/onelua.c",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_lua.Prepend(CPPPATH=[thirdparty_dir + "lua"])

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

module_obj = []

env_lua.add_source_files(module_obj, "*.c")
env_lua.add_source_files(module_obj, "types/*.c")
env.modules_sources += module_obj

env.Depends(module_obj, thirdparty_obj)
