#!/usr/bin/env python

Import("env")

source_files = [
    "wayland_server.c",
    "wayland_window.c",
    "xdg-shell.gen.c",
]

objects = []

for source_file in source_files:
    objects.append(env.Object(source_file))

Return("objects")