#!/usr/bin/env python

from renderer_builders import make_shader_source
Import("env")
env.AddMethod(make_shader_source, "make_shader_source")

env.renderer_sources = [
    "renderer.c",
    "context.c",
    "window.c",
    "shader.c",
    "buffers.c",
    "vertex_array.c",
    "texture.c",
    "camera.c",
    "sprite.c",
    "sprite_object.c",
    "batch_renderer.c",

    "batch_shader.gen.c",
]

env.make_shader_source("renderer/shaders/batch.shader", "BATCH_SHADER_SOURCE", "renderer/batch_shader.gen.c")

if env["use_opengl"]:
    SConscript("opengl/SCsub")

lib = env.add_library("renderer", env.renderer_sources)
env.Prepend(LIBS=[lib])
