#!/usr/bin/env python

Import("env")

env.renderer_sources = [
    "renderer.c",
    "context.c",
    "window.c",
    "shader.c",
]

if env["use_opengl"]:
    SConscript("opengl/SCsub")

lib = env.add_library("renderer", env.renderer_sources)
env.Prepend(LIBS=[lib])
