#ifndef RENDERER_TYPEDEFS_H
#define RENDERER_TYPEDEFS_H

typedef enum {
	USAGE_HINT_STREAM_DRAW = 0,
	USAGE_HINT_STREAM_READ,
	USAGE_HINT_STREAM_COPY,
	USAGE_HINT_STATIC_DRAW,
	USAGE_HINT_STATIC_READ,
	USAGE_HINT_STATIC_COPY,
	USAGE_HINT_DYNAMIC_DRAW,
	USAGE_HINT_DYNAMIC_READ,
	USAGE_HINT_DYNAMIC_COPY,
} UsageHint;

typedef enum {
	TARGET_HINT_ARRAY_BUFFER = 0,
	TARGET_HINT_ELEMENT_ARRAY_BUFFER,
	TARGET_HINT_PIXEL_PACK_BUFFER,
	TARGET_HINT_PIXEL_UNPACK_BUFFER,
	TARGET_HINT_UNIFORM_BUFFER,
	TARGET_HINT_TEXTURE_BUFFER,
	TARGET_HINT_TRANSFORM_FEEDBACK_BUFFER,
	TARGET_HINT_COPY_READ_BUFFER,
	TARGET_HINT_COPY_WRITE_BUFFER,
} TargetHint;

typedef enum {
	DATA_TYPE_BYTE = 0,
	DATA_TYPE_UNSIGNED_BYTE,
	DATA_TYPE_SHORT,
	DATA_TYPE_UNSIGNED_SHORT,
	DATA_TYPE_INT,
	DATA_TYPE_UNSIGNED_INT,
	DATA_TYPE_FLOAT,
	DATA_TYPE_DOUBLE,
} DataType;

typedef enum {
	DRAW_MODE_POINTS = 0,
	DRAW_MODE_LINE_STRIP,
	DRAW_MODE_LINE_LOOP,
	DRAW_MODE_LINES,
	DRAW_MODE_LINE_STRIP_ADJACENCY,
	DRAW_MODE_LINES_ADJACENCY,
	DRAW_MODE_TRIANGLE_STRIP,
	DRAW_MODE_TRIANGLE_FAN,
	DRAW_MODE_TRIANGLES,
	DRAW_MODE_TRIANGLE_STRIP_ADJACENCY,
	DRAW_MODE_TRIANGLES_ADJACENCY,
	DRAW_MODE_PATCHES,
} DrawMode;

#endif // RENDERER_TYPEDEFS_H