#!/usr/bin/env python

Import("env")

env.Append(CPPPATH=[
    "#thirdparty/glad",
])

env.add_source_files(env.renderer_sources, "#thirdparty/glad/egl.c")

env.add_source_files(env.renderer_sources, "#thirdparty/glad/gles2.c")
env.add_source_files(env.renderer_sources, "#thirdparty/glad/gl.c")

env.add_source_files(env.renderer_sources, "*.c")