#!/usr/bin/env python
import sys

Import("env")

if env.opengl_mode == "gl":
    env.Append(CPPDEFINES=["OPENGL_MODE_GL"])
elif env.opengl_mode == "gles":
    env.Append(CPPDEFINES=["OPENGL_MODE_GLES"])

if env.opengl_context == "egl":
    SConscript("egl/SCsub")
elif env.opengl_context == "wgl":
    SConscript("wgl/SCsub")
else:
    print("Unknown OpenGL context method: " + env.opengl_context)
    sys.exit(255)

env.Append(CPPDEFINES=["OPENGL_ENABLED"])