#!/usr/bin/env python
import sys

Import("env")

env.Append(CPPDEFINES=["OPENGL_ENABLED"])

if env["platform"] != "windows":
    SConscript("egl/SCsub")
else:
    SConscript("wgl/SCsub")

env.add_source_files(env.renderer_sources, "*.c")