#!/usr/bin/env python

Import("env")

common_linuxbsd = [
    "linuxbsd_os.c",
    "linuxbsd_os_window.c",
]

if env["use_wayland"]:
    common_linuxbsd += SConscript("wayland/SCsub")

if env["use_x11"]:
    common_linuxbsd += SConscript("x11/SCsub")

prog = env.add_program("#bin/lunar_sprites", ["lunar_sprites_linuxbsd.c"] + common_linuxbsd)
