name: 🐧 Linux
on:
  workflow_call:

env:
  BASE_BRANCH: main
  SCONS_CACHE_LIMIT: 7168

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    name: 🐧 Linux build
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        shell: sh
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev libegl1-mesa-dev yasm

      - name: Install buildroot x86_64
        shell: sh
        run: |
          cd /opt
          curl -LO https://downloads.tuxfamily.org/godotengine/toolchains/linux/2021-02-11/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar xf x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          rm -f x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          mv x86_64-godot-linux-gnu_sdk-buildroot buildroot
          cd buildroot
          ./relocate-sdk.sh

      - name: Load .scons_cache directory
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: linux-amd64-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            linux-amd64-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            linux-amd64-${{env.BASE_BRANCH}}-${{github.ref}}
            linux-amd64-${{env.BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Build Lunar Sprites
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          PATH=/opt/buildroot/bin:$PATH scons platform=linuxbsd target=debug arch=x86_64 dev_build=yes

      - name: Copy Docs
        run: |
          cp README.md bin/
          cp LICENSE.md bin/

      - uses: actions/upload-artifact@v3
        with:
          name: linux-debug
          path: bin/*
